### ISSUE TITLE
未找到alipay的jar包

### ISSUE THREAD

**Issue by zhongmax** [luqinmao/storeClient#1]
你好！
我使用maven将依赖导入后，在import中，提示alipay.api与alipay.demo未找到，在pom文件中也没有找到alipay的依赖，请问这个是需要单独配置的吗？

**Comment by luqinmao** [comment]
看了在resources/lib目录下，引入项目就行了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "maxwell"; 
发送时间: 2019年11月18日(星期一) 中午11:23
收件人: "luqinmao/storeClient";
抄送: "Subscribed";
主题: Re: [luqinmao/storeClient] 未找到alipay的jar包 (#1)




Closed #1.
 
&mdash;
